### ISSUE TITLE
Building `dist/OCA.es5.js` on develop branch fails

### ISSUE THREAD

**Issue by dbrignoli** [DeutscheSoft/OCA.js#2]
What am I doing wrong? Going back as far as the commit which introduced the target (f930a3906ea747d18ed323a4ef92e900073452d9) doesn't help. Thank you.

```
⟫ make
rollup --o dist/rollup.js --f iife -c rollup.conf.js src/index.js -m dist/rollup.js.map

src/index.js → dist/rollup.js...
created dist/rollup.js in 1.9s
BABEL_ENV=browser babel dist/rollup.js -o dist/babel.browser.js
[BABEL] Note: The code generator has deoptimised the styling of "dist/rollup.js" as it exceeds the max of "500KB".
closure-compiler --js dist/babel.browser.js --js_output_file dist/OCA.es5.js --language_in ECMASCRIPT5 --language_out ECMASCRIPT5
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Makefile:34: recipe for target 'dist/OCA.es5.js' failed
make: *** [dist/OCA.es5.js] Error 1
```

**Comment by dbrignoli** [comment]
closure-compiler requires java which was not installed. I also found AES70.js repo which has been updated more recently so I am closing this issue switching to that.
